project:
  type: website

website:
  title: "Hockey Data Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Shot_Location.qmd
      - Type_Of_Goal_Bar.qmd
      - Time_Playing_VS_Goals.qmd
      - Hockey-Shot-Overview-Sources.qmd
      - about.qmd
format:
  html:
    theme: cosmos
    css: styles.css
    toc: true



